name: docs
on:
  push:
    branches:
      - main
      - v*
env:
  LATEST_VERSION: v0.4
  
jobs:
  master-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - run: |
          git config --global user.name opni
          git config --global user.email docs@opni.bot
          git pull
      - run: |
          mike deploy ${{ env.LATEST_VERSION }}
          mike set-default ${{ env.LATEST_VERSION }}
          mike deploy --rebase --push --update-aliases ${{ env.LATEST_VERSION }} latest
          
  version-build:
    if: startsWith(github.ref, 'refs/heads/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: echo "::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)"
        id: info
      - run: pip install mkdocs-material mike
      
      - run: |
          git config --global user.name opni
          git config --global user.email docs@opni.bot
          git pull
      - run: mike deploy --rebase --push ${{ steps.info.outputs.version }}
